services:
  - type: web
    name: mfa-app
    env: python
    plan: free
    buildCommand: |
      curl -sLo miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"

      conda create -y -n mfa python=3.9
      source $HOME/miniconda/bin/activate mfa

      conda install -y -c conda-forge montreal-forced-aligner ffmpeg cmake make pkg-config sentencepiece

      pip install flask gunicorn gtts pandas

    startCommand: |
      source $HOME/miniconda/bin/activate mfa && gunicorn app:app

